### ISSUE TITLE
dlopen failed: library "libxgd_ddi_jni.so" not found

### ISSUE THREAD

**Issue by sonhnInves** [judahben149/EMVSync#2]
I can not build application
![Screenshot 2024-01-11 004934](https://github.com/judahben149/PayBuddy/assets/129050636/a0e8b832-7dbf-4908-a0e5-90c69c88d3d7)

**Comment by judahben149** [comment]
Because the app is bundled with the Nexgo SDK library, you cannot run the app on a regular Android device.
You can only run it on a Nexgo POS terminal device.
